### ISSUE TITLE
Subscribing to all favourites

### ISSUE THREAD

**Issue by kiduut** [bstrdsmkr/1Channel#163]
How about adding functionality that will subscribe to all web favourites? Ofcourse it should check if there are any updates on tv show. It's pretty breathtaking when you need to subscribe to many favourite tv shows one by one. I could try doing it without checking if there has been any updates.

**Comment by kiduut** [comment]
What do you about it guys?

**Comment by tknorris** [comment]
I'm not a fan. I don't think it would be very useful. We already have the ability to use a playlist for subscriptions which means they only have to be setup one time.

**Comment by kiduut** [comment]
Oh didnt know that. Well, with favourites you have tv schedule, so to me favourites should suite better as primary list where to subsubscribe to all. Also pw doesnt seem to have feature to add all favourites to playlist. So still users have to do double activity. But since i managed to subscribe already to all my 77 favourite shows, im ok about your opinion.

**Comment by tknorris** [comment]
ok, I'm going to close this issue then. Thanks for the suggestion though!

**Comment by kiduut** [comment]
If I find more time, then ill try to fork and add the feature:)

**Comment by tknorris** [comment]
sure. PRs are always welcome
