### ISSUE TITLE
Problem 1chanel 

### ISSUE THREAD

**Issue by yousef1991y** [bstrdsmkr/1Channel#184]
Hi 
I have problem with 1chanel 
Iam download last update kodi and 1chanel 2.5.60
I cant wath any movie 
This problem " No sources were found this item"
And this log 
Your debug xbmc.log: http://xbmclogs.com/show.php?id=383115
Your XBMC crashlog: http://xbmclogs.com/show.php?id=383116

**Comment by tknorris** [comment]
Are you still having this issue? If not I'll close it.

**Comment by brocksrad** [comment]
Also having this issue

**Comment by tknorris** [comment]
I need a log.

**Comment by brocksrad** [comment]
I've got the onechannelcache.db file but can't figure out how to load it here. Email?

**Comment by tknorris** [comment]
There is no reason for you to do that. The whole PrimeWire site is **DOWN**. The addon will not work as long as the site is down: http://www.primewire.ag/

**Comment by brocksrad** [comment]
Oooooh, lol. Well thanks for the clarification. Didn't realize that's what you meant
