### ISSUE TITLE
Update library after manual add_to_library()?

### ISSUE THREAD

**Issue by ashtonaut** [bstrdsmkr/1Channel#189]
This is a minor feature request, not a bug.

I wondered if it's possible to add a Kodi UpdateLibrary() call at the end of the add_to_library() function in default.py (around line 1557 maybe?).

Every time I manually add something to the Kodi library from 1Ch, I then need to manually navigate into the library and refresh it so that the new addition will show up. Automating a library refresh after adding a new show/movie to the library would remove this manual step, and the newly added content would appear immediately.

I believe it is possible to specify the specific folder path that the new .strm file(s) have been written to in the UpdateLibrary() call, so making this change would only trigger a partial library refresh, not a full refresh.

I can't think of a usage case where this behaviour wouldn't be advantageous, but if one exists then I'm happy to hear it.

**Comment by tknorris** [comment]
The only reason not to do it would be for slow hardware (like the rpi). What I can do is respect the update library setting in subscriptions.

**Comment by ashtonaut** [comment]
I understand the sentiment about low power hardware, but the whole point of adding a show to the library is to see it there, so the refresh needs to happen sooner or later :) (I'm on a RPi BTW). Also from my experience the library refresh runs 'in the background', so I should be able to continue to navigate menus while it happens. Using the library update setting from subscriptions is a good idea, perhaps just change the setting wording so it's clear.

Out of interest, is the post-sub update refresh a full refresh, or only the folders that have had strm files added? I imagine the latter would be much faster, which is why I suggested only refreshing the specific path that the strms have been added to.

Anyway, thanks for considering this.

**Comment by tknorris** [comment]
It's a video refresh. XBMC skips folders that don't have updates.

I've had nothing but problems w/ trying to limit the library update to only a subset of folders. It consistently fails to find updates when only run for a folder. I had to dump the use of Library Watchdog because it does this and NEVER works for me on Linux.

**Comment by ashtonaut** [comment]
Interesting, I didn't realise the UpdateLibrary() function had that intelligence.

I tried library watchdog to get around the issue but on my RPi there was a massive performance hit so I uninstalled it.

**Comment by s7eele** [comment]
why have i never bothered looking here, good info, just saw the new tag (?) and wanted to see whats been happening over here the whole time

**Comment by ashtonaut** [comment]
I still haven't had the time to try and modify and test this myself. I think it's a simple change.  if I ever get the time I'll try to have a go myself.

**Comment by vile80r** [comment]
Has this feature been looked further into? I just found this by Googling "1channel add-on update library after adding content".  Genesis does this,  it's optional in the settings along with an "auto update TV shows" option. I do like when I add a new series to the library it immediately starts grabbing info and images etc. 

However,  I prefer 1channel over Genesis. The host sorting options are fantastic which makes the auto play function fantastic. I just dont care for the need to add a show then have to go manually run the update. It is a very small feature but,  very convenient. 

Regardless,  great work.
