### ISSUE TITLE
Quality TAG from PrimeWire website

### ISSUE THREAD

**Issue by TerrorKeed** [bstrdsmkr/1Channel#191]
Is it possible to drag the quality type of the current movie and use on primewire? instead of marking everything as DVD?

I.E
![dear](https://cloud.githubusercontent.com/assets/6576071/5890981/18426df6-a47a-11e4-8469-bb3232002cd4.PNG)
![inter](https://cloud.githubusercontent.com/assets/6576071/5890980/183d3c46-a47a-11e4-930b-d939fa85e838.PNG)
![tak3n](https://cloud.githubusercontent.com/assets/6576071/5890982/1859ef6c-a47a-11e4-9041-8c4852a5f664.PNG)
![wick](https://cloud.githubusercontent.com/assets/6576071/5890983/185d19f8-a47a-11e4-8b5c-c7d0663e7dd9.PNG)

Iike in this screenshot
![links](https://cloud.githubusercontent.com/assets/6576071/5890988/fd5a3cd4-a47a-11e4-8e5c-1a5f3cd43df0.PNG)
 
would be a nice feature, thanks

**Comment by tknorris** [comment]
We pull the quality from the tag at the beginning of each source, not the header. The header isn't consistent or accurate.
