### ISSUE TITLE
Known Best Source sorting

### ISSUE THREAD

**Issue by TerrorKeed** [bstrdsmkr/1Channel#192]
Sort a maximum 5 Known Hosts in a List and Sort in order of preference,
It would be on a different settings TAB name Host Sorting

it would be a box containing all the known primewire host
each one you tick would un-grey a box which you would then select the hosts, up-to and not more than 5 times, that way when someone ticks auto-play sources it just picks the streams in the other your configured which in my opinion the ones i selected are the one's that best for me and i use regularly

It will pick in descending order from 1 to 5 in a scenario where the particular stream doesn't have the first host configured it fallsback to host #2 and so on till it plays

This is a quick rough/mockup to show you what i mean
![sources](https://cloud.githubusercontent.com/assets/6576071/5891047/d02b17f2-a47e-11e4-892f-83b019f0ca1f.PNG)

it will be user configured

**Comment by TerrorKeed** [comment]
In a case where a configured host appears multiple times they should be sub-sorted
promptfile
 #1
 #2
Sharesix
 #1
 #2

It'll be great it this is done, tknorris this has been on my mind for a while now and i thought about it alot and finally decided it was time to let you look into it...

i will be here to provide inputs in-case you don't get my point somewhere. IMHO this will greatly improve the auto-play feature

**Comment by tknorris** [comment]
Autoplay already respects your sort order, and it's possible to provide a sort order for hosts.
