### ISSUE TITLE
1channel sources not loading

### ISSUE THREAD

**Issue by smellybaws** [bstrdsmkr/1Channel#193]
My 1channel has recently stopped working. I'm getting all the way through to picking an episode but nothing happens when the list of sources is supposed to appear.
I have an XBMC backup which i have installed a few times, 1channel works perfectly until the other addons update and then it stops loading sources again. I think something is conflicting it but i can't figure out what...

**Comment by tknorris** [comment]
Post a log of trying to play an episode.

**Comment by smellybaws** [comment]
I've done it 3 times now and still not received an email

**Comment by smellybaws** [comment]
https://docs.google.com/file/d/0B1wFXIUYvN4zYWxjaHloUU1zcE0/edit

**Comment by tknorris** [comment]
If you want me to view it, you need to grant access to public.

**Comment by smellybaws** [comment]
Sorry, that should be ok now

**Comment by tknorris** [comment]
Install this zip in XBMC/Kodi and let me know if it fixes your problem: https://github.com/Eldorados/Core-Module-Beta-Repo/blob/master/repo/script.module.urlresolver/script.module.urlresolver-2.7.2.zip?raw=true

**Comment by smellybaws** [comment]
That looks to have done the trick mate, thanks very much :-)
