### ISSUE TITLE
Subtitles not appearing

### ISSUE THREAD

**Issue by kiduut** [bstrdsmkr/1Channel#194]
After launching a show or movie and selecting subtitle from "Download subtitles", subtitles dont appear:(

**Comment by tknorris** [comment]
That function is a standard XBMC function, not an addon function.

**Comment by kiduut** [comment]
But they appear for any other source than 1channel?:/

**Comment by tknorris** [comment]
It's still an XBMC function. It has nothing to do w/ 1CH

**Comment by kiduut** [comment]
Ok, ill try to troubleshoot the problem tomorrow thoroughly.

**Comment by tknorris** [comment]
FYI, I took a second to try this and it worked fine here.

**Comment by tuxen** [comment]
Just a comment and heads up,
Yes they work fine, I know people that wouldn't be able to understand any of the content if not.
