### ISSUE TITLE
Search field is wrong filetype/mime-type

### ISSUE THREAD

**Issue by tuxfuxch** [bstrdsmkr/1Channel#195]
Hi
while developing a solution to browse the addon over a webinterface, i face a wrong beheivioir.

The search field (exeample: TV shows -> Search) comes over json/rpc as "mimetype ": "application/octet-stream" and "filetype": "file". so it thinks it has to start something.

if it would be "x-directory/normal" and "directory", the addon could fetch the results (like it does on other plugins). i really hope you guy's can change that, would be great!

**Comment by tknorris** [comment]
We can't change that. That's done to prevent the search query from being added to the crumbtrail. If it comes back as directory, then when you go back you would get to a point where the search dialog popped up again.

**Comment by tuxfuxch** [comment]
hm... that's said. well hope one day there is a solution for that. so long i close the issue.
