### ISSUE TITLE
HTTPS support for Primewire links

### ISSUE THREAD

**Issue by DoctorOctagonapus** [bstrdsmkr/1Channel#196]
I live in the UK, where most links to Primewire/1Channel are censored by the Glorious Regime, but some HTTPS links are not yet blocked. I've tried various HTTPS links as custom URLs but none of them work. Does this plugin support HTTPS URLs?

**Comment by hmemar** [comment]
hi Doctor try this guide https://www.youtube.com/watch?v=f2V7vUt1qyU 
I am in the uk and when I made this it worked well for me for primewire

**Comment by tknorris** [comment]
Yes, you should be able to use https proxy urls. I'm aware of several users having done so.
