### ISSUE TITLE
Getting metadata

### ISSUE THREAD

**Issue by ydyote** [bstrdsmkr/1Channel#203]
TVseries American dad episodes are on primewire different as on thetvdb.com

the bug is that metadata are from  thetvdb but it is not the same as primewire (imdb)

i reported this to thetvdb and they replied with:
"That is not a bug.
viewtopic.php?f=7&t=6308"

so im reporting it here because metadata fetching lacks some kind of validation if thetvdb and imdb episodes matches

this is a really big problem when u want to use library integration because episodes dont even appear there (because HTTP404 and returns no metadata whatsoever) (i made a workaround but it doesnt fix wrong names just uses episode titles from 1chDatabase when meta['title'] == '')

http://thetvdb.com/?tab=season&seriesid=73141&seasonid=5356&lid=7
http://www.imdb.com/title/tt0397306/episodes?season=1

on thetvdb season 2 starts with S1E8 on imdb (primewire)

Thanks, ur the best

**Comment by tknorris** [comment]
This is just one of those "that's the way it is" kind of things. There's no requirement that PW and TVDB match.

**Comment by ydyote** [comment]
Mm ok and just for info could you tell me why the plugin is using tvdb for meta instead of imdb?

**Comment by tknorris** [comment]
1) Because that's what metahandler uses 2) IMDB doesn't have a public API but TVDB does 3) TVDB is the default TV scraper for Kodi.

**Comment by ydyote** [comment]
ok thx
